### ISSUE TITLE
Problem with Light objects

### ISSUE THREAD

**Issue by CliffS** [AlCalzone/node-tradfri-client#10]
I've had problems with calling the methods directly on the Light class.

First of all, I think the tests at lines 213, 227, 241 and 255 are reversed.  For example:
```TypeScript
if (this.spectrum === "white") throw new Error("setColorTemperature is only available for white spectrum lightbulbs");
```
Beyond that, I've been unable to get the functions to operate the bulb although calling `operateLight()` directly seems to work as expected.

**Comment by AlCalzone** [comment]
Hmm that seems wrong. I'll take a look at it but I cannot guarantee when - this week is going to be busy.

**Comment by AlCalzone** [comment]
Should be fixed now. Feel free to reopen if it didn't.
