### ISSUE TITLE
Add support for Smart Plugs

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-tradfri-client#111]
Example log output (truncated):
```
tradfri.0	2018-10-01 13:28:56.061	warn	Unknown accessory type 3. Please send this info to the developer with a short description of the device!
tradfri.0	2018-10-01 13:28:56.061	warn	object was: {"3":{"0":"IKEA of Sweden","1":"TRADFRI control outlet","2":"","3":"1.4.020","6":1},"3312":[{"5850":0,"5851":254,"9003":0}],"5750":3,"9001":"Uttag","9002":1538388215,"9003":65541,"9019":1,
tradfri.0	2018-10-01 13:28:56.061	warn	found unknown property with key 9084
```

```
{"3":{"0":"IKEA of Sweden","1":"TRADFRI control outlet","2":"","3":"1.4.020","6":1},"3312":[{"5850":0,"5851":254,"9003":0}],"5750":3,"9001":"Uttag","9002":1538388215,"9003":65541,"9019":1,"9020":1540211625,"9054":0,"9084":" 6c ba 7f 97 47 8e 75 88 10 20 29 30 60 a9 3b 7d"}
```

**Comment by rogierhofboer** [comment]
Good to see are working on this 👍 
I just checked before starting to work on it myself (so we don't do the same thing).
But please let me know if you need help with this!

I will integrate plug support into the Athom Homey app as soon as this module is finished.

**Comment by AlCalzone** [comment]
This PR should be working already, but I won't merge it before I've added the component tests.
If you want to give it a test-run (as I don't have any plugs yet), please feel free to do so.

**Comment by rogierhofboer** [comment]
Do you plan to add a convenience method to operate the plugs i.g. operatePlug?

**Comment by AlCalzone** [comment]
Yes, Plugs should be in line with lights from a usage point of view

**Comment by AlCalzone** [comment]
I know, I just had a little time to spare. If you like, you can create a PR on this branch so I can get in included here.
