### ISSUE TITLE
Re-connect

### ISSUE THREAD

**Issue by laurilubi** [AlCalzone/node-tradfri-client#12]
Is there a way to detect that the connection to Ikea gateway has been lost and that I need to reconnect? I restarted the Ikea gateway today and just stopped receiving the event that I subscribe on.

**Comment by AlCalzone** [comment]
[`ping()`](https://github.com/AlCalzone/node-tradfri-client#pinging-the-gateway) and [`reset()`](https://github.com/AlCalzone/node-tradfri-client#resetting-the-connection) are your friends.

**Comment by laurilubi** [comment]
Thank you! Now I have support for automatic re-connect and seems to work nice.
