### ISSUE TITLE
Changing brightness while light is off

### ISSUE THREAD

**Issue by jareware** [AlCalzone/node-tradfri-client#122]
I'm pretty sure there's no way of doing this, but just to make sure: is there a way to achieve this:

1. A lamp is at 100% brightness
1. It's turned off from a physical remote
1. ✨ doing something here ✨ 
1. It's turned on from a physical remote
1. The lamp powers on at 10% brightness

?

Things I've tried:

* Using `.setBrightness()` while the lamp is off, but that will power it on
* Using `.toggle(false)` a few ms after `.setBrightness()`, but that gives inconsistent results
* Sending the raw command as the combination of brightness setting and powering off (e.g. `{"3311":[{"5712":5,"5850":0,"5851":3}]}`) but that doesn't work
* Waiting for the event on the gateway of the lamp powering on, and then reacting to that by immediately using `.setBrightness()`, but you can briefly see the 100% brightness before it dims down to 10%

The only reason I'm asking is that [this person on Reddit](https://www.reddit.com/r/tradfri/comments/7gw0ns/how_to_automatically_set_bulbgroup_intensity/dqm8tym) speaks as if it's possible... but is it?

**Comment by AlCalzone** [comment]
I'm pretty certain that is not possible. Any brightness change to a value > 0 turns the bulb on as you have noticed. The only way I could imagine is a sequence of commands, all with a transition time of 0:
- power on
- set brightness
- power off
But this will probably result in a noticeable blink of the light.

**Comment by jareware** [comment]
> But this will probably result in a noticeable blink of the light.

Indeed it did.

> triggering the state change when turning on

Yeah, this seems the way to go. Not perfect but least ugly.

Thanks for your input!
