### ISSUE TITLE
Outlets Ikea

### ISSUE THREAD

**Issue by Jer3m** [AlCalzone/node-tradfri-client#126]
Hello,

Do outlet works with this plugin ?

Regards

Jeremie

**Comment by AlCalzone** [comment]
They should, yes. It they don't, please create an issue here.

**Comment by Jer3m** [comment]
Ok I will.
Thanks for answer.

**Comment by petternordholm** [comment]
@Jer3m Just bought on Ikea Trådfri Outlet and it works perfectly with this api.

**Comment by AlCalzone** [comment]
Good to know, thanks!
