### ISSUE TITLE
Add support for blinds

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-tradfri-client#127]

**Comment by justme-1968** [comment]
i have just integrated the blind support from note-tradfri-client into tradfri-fhem (https://github.com/justme-1968/tradfri-fhem) and it works great! thanks for this.

but i have one remark: i think blinds up should be 100% and blinds down should be 0%. most other home automation systems do it this way and homekit also. i've come to see it as: if it is bright the percentage ist high. like a lightbulb.

are the current inverted values reported directly  by the gateway? then keep them.
or are they inverted somewhere in node-tradfri-client? then i think they should be reversed.

**Comment by AlCalzone** [comment]
No the values are apparently what the gateway reports. This library doesn't do any reversing yet. I'll think about it, since the color temperature is also mapped to 0..100%.

**Comment by justme-1968** [comment]
one more thing: is there a stop command? i have found open, close and setPosition. the Ikea app allows stopping so it must be somewhere.

**Comment by AlCalzone** [comment]
Might be... I'll take a look at the newest app later.

**Comment by AlCalzone** [comment]
@justme-1968 I moved your concern to a new issue. If you could find out what the app sends to the gateway it would help me a lot since I don't have any blinds.

**Comment by AlCalzone** [comment]
@justme-1968 as of v2.0.0, position 0 now means closed, 100 means open.
That version will be released in a couple of minutes
