### ISSUE TITLE
Issue running client on Windows 10, Node 11

### ISSUE THREAD

**Issue by dgoemans** [AlCalzone/node-tradfri-client#129]
I'm installing the client in a minimal nodejs/express project on Windows 10, using Node 11.
Client installs, but doesn't seem to skip the `node-aead-crypto` library. 
```
ERROR in ./node_modules/node-dtls-client/build/lib/AEADCrypto.js
Module not found: Error: Can't resolve 'node-aead-crypto' in 'D:\Projects\NetworkDashboard\node_modules\node-dtls-client\build\lib'
 @ ./node_modules/node-dtls-client/build/lib/AEADCrypto.js 54:46-73
 @ ./node_modules/node-dtls-client/build/TLS/AEADCipher.js
 @ ./node_modules/node-dtls-client/build/TLS/CipherSuite.js
 @ ./node_modules/node-dtls-client/build/DTLS/Handshake.js
 @ ./node_modules/node-dtls-client/build/dtls.js
 @ ./node_modules/node-coap-client/build/CoapClient.js
 @ ./node_modules/node-tradfri-client/build/tradfri-client.js
 @ ./node_modules/node-tradfri-client/build/index.js
 @ ./src/ikea/Tradfri.js
 @ ./src/index.js
 @ multi babel-polyfill ./src/index.js
```

I've tried a bunch of options, including installing all the deps on their own, excluding the library. Some things that might be relevant to my usage:
- Using Babel to transpile ES6 modules to something that node can handle
- Using Webpack as my build tools

Any thoughts?

**Comment by dgoemans** [comment]
So here's a nasty trick...
Using `nvm` i switched back to node `v8.15.1`, installed the package. It didn't run, failed somewhere inside the `aead` module. Then switched back to node `v11.10.1`, and BAM, it worked.

This makes me both sad and happy at the same time.

**Comment by AlCalzone** [comment]
This should be fixed with the newer releases of `node-aead-crypto`. Feel free to reopen if not.
