### ISSUE TITLE
await not working

### ISSUE THREAD

**Issue by riksnelders** [AlCalzone/node-tradfri-client#162]
I cant seem to use 

const result = await discoverGateway();

but can use discoverGateway().then()

**Comment by AlCalzone** [comment]
Can you share at least a minimal repro or an error description? I can't help you with the information you provided.

**Comment by riksnelders** [comment]
Await is reserved keyword and I am using babel. 

seems its not recognized as a async function, nor can I find async anywhere in the package ? 
Don't have code right now, Probably messing up, but I assume the code on top of the readme should work.

**Comment by AlCalzone** [comment]
It has nothing to do with this library. You can only use await inside async functions.
