### ISSUE TITLE
Network reset?

### ISSUE THREAD

**Issue by realjax** [AlCalzone/node-tradfri-client#209]
Hi
I have the following situation ( using auto reconnect):

- I start a connection to a gateway
- I set a bunch of observers (gateway, devices, groupsAndScene and notifications)
- on the "connection lost" update I stop all above mentioned observers

But then, as soon as first reconnect attempt is made  i get this:
`UnhandledPromiseRejectionWarning: Error: The network stack was reset. Pending promises will not be fulfilled`

Which I dont understand.. was stopping the observers not sufficient?  And where am I to catch/handle this error, on what promise? I tried on the 'connect' promise but that wasn;t the correct one from the looks of it..

Thanks.

**Comment by AlCalzone** [comment]
Do you have an event handler set up for the "error" event? If not, you should. You can then swallow the error there:
https://github.com/AlCalzone/ioBroker.tradfri/blob/master/src/main.ts#L643

It mostly informative, but the mentioned error is disruptive enough that I want developers to catch it.

**Comment by realjax** [comment]
Thanks, hadn't set that one up yet. I will try it out !

**Comment by realjax** [comment]
Thanks, worked fine. Does this also capture the error as mentioned in #108 by any change ?

**Comment by AlCalzone** [comment]
I'm not sure actually. Those DNS errors sometimes happen in internal callbacks I have no control over.
I remember some changes a while ago where I explicitly stopped using the internal DNS lookup methods for that reason. But it might be that I missed a spot.
