### ISSUE TITLE
Question regarding hostname

### ISSUE THREAD

**Issue by oscarnyl** [AlCalzone/node-tradfri-client#22]
Is there supposed to be some form of discovery of the hostname of the Trådfri Gateway? My current workaround is that I have mapped in the IP address of the gateway to the hostname in my docker-compose file (the 'extra_hosts'-key), but judging from the examples it seems like it should work without any intervention. Am I missing something? Just a little confused about this.

**Comment by AlCalzone** [comment]
Hmm I guess I could write this in the readme. The hostname is `"gw-"` followed by the MAC address in lowercase without any separators. The MAC address is printed on the label under the gateway.

**Comment by oscarnyl** [comment]
That is how I assumed it was: However, I was unable to connect when only entering the hostname (ERR_NAME_NOT_RESOLVED).

My case might be slightly special though as I'm running the development inside a Docker container which in turn is ran on a virtual machine :sweat_smile:

**Comment by AlCalzone** [comment]
Hmm, can you open the console on your machine and run `node`, then enter the following code (edit the hostname)
```js
var dns = require("dns");
dns.resolve("gw-xyzabc", function(err, addr) {
	if (err) {
		console.log("ERROR: " + err);
	} else {
		console.log(JSON.stringify(addr));
	}
});
```
and post the output here? I'd need some more info as I haven't heard about that error in a nodejs context.

**Comment by oscarnyl** [comment]
I think I've figured out why it would not resolve: I'm running a pihole in my network as my DNS server, which apparently messes with how this is supposed to work. When the pihole is inactive the adress resolves correctly, output of command is:
```
dns.resolve('gw-dcefcabcf84d', (err, addr) => err ? console.log(err) : console.log(JSON.stringify(addr)))
// => ["192.168.1.55"]
```

**Comment by oscarnyl** [comment]
I wonder if I can get it to work automatically while still having the pihole present on the network.

**Comment by oscarnyl** [comment]
For reference this is the result when running the same code when the pihole is active:

```
dns.resolve('gw-dcefcabcf84d', (err, addr) => err ? console.log(err) : console.log(JSON.stringify(addr)))
// => { Error: queryA ENOTFOUND gw-dcefcabcf84d
    at errnoException (dns.js:55:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:243:19)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'queryA',
  hostname: 'gw-dcefcabcf84d' }
```

**Comment by AlCalzone** [comment]
Maybe enabling the pi-hole's DHCP helps with that:
https://www.reddit.com/r/pihole/comments/5xepzl/local_hostname_resolution/
Or you can add the gateway to /etc/hosts on the pihole:
https://discourse.pi-hole.net/t/trouble-using-pihole-to-resolve-local-hostnames/2163/2

Closing this as it doesn't seem to be a library issue.

**Comment by oscarnyl** [comment]
Thank you for the suggestion, I will try that out. :+1:
