### ISSUE TITLE
operateLight() switches light on and off unexpectedly

### ISSUE THREAD

**Issue by realjax** [AlCalzone/node-tradfri-client#231]
When I use this lightoOperation object on a non-spectrum light :

`{
    dimmer: number
  }`

It also toggles the light.  I mean. I expected it to turn on when it was in the off state, but I didn't expect it to turn off too  when it is on?? ( when receiving the above object)

I expected it to do nothing at all the second (or third, or fourth) time it was sent because , in effect, nothing had changed and I thought no commands where sent if that's the case?

**Comment by AlCalzone** [comment]
Which dimmer values are you sending when the light toggles?

**Comment by realjax** [comment]
I used 50 and 25. 

AlCalzone <notifications@github.com> schreef op 6 augustus 2019 23:33:45 CEST:

**Comment by AlCalzone** [comment]
That sounds strange. I have also never heard any reports of this.
Can you give me a minimal code example where this happens?

**Comment by AlCalzone** [comment]
Hey there, anything new?

**Comment by realjax** [comment]
No sorry, havent had time yet to investigate this any further yet. :(

**Comment by realjax** [comment]
Closed, behaviour was cause by sending a lightOperation object with values 'undefined'

**Comment by AlCalzone** [comment]
I should validate the objects I guess
