### ISSUE TITLE
Some accessory properties missing when parsing it to JSON

### ISSUE THREAD

**Issue by kelrien** [AlCalzone/node-tradfri-client#267]
Hi there ! I am currently working on a web interface for controlling my gateway via webinterface and am using this module on the server side.

What i discovered is that when using JSON.stringify to serialize them (express does this when using response.json) some of the properties of an accessory are missing (for example the `isDimmable` and `spectrum` properties)

I worked around this by adding those properties manually before sending them out as a response. Would it be possible to add those properties to the `toJSON` function inside the light accessory?

**Comment by kelrien** [comment]
If this is something that sounds nice but is currently not on your plate i could do the changes myself and send you a PR.

**Comment by AlCalzone** [comment]
Sounds good! Feel free to provide a PR, since my time is focused on a different project currently.

**Comment by kelrien** [comment]
Sure thing! Thanks for the fast response!

**Comment by kelrien** [comment]
@AlCalzone merge request sent!
