### ISSUE TITLE
How to read the dim value of the wireless dimmer remote?

### ISSUE THREAD

**Issue by tundratier** [AlCalzone/node-tradfri-client#273]
Is it possible to read the state of the [wireless dimmer remote](https://www.ikea.com/de/de/p/tradfri-kabelloser-dimmer-weiss-00347831/)?

`device updated` does not trigger when I rotate the dimmer.

**Comment by AlCalzone** [comment]
Sadly this is not possible. The gateway does not send any information about the remote.

**Comment by WillooWisp** [comment]
For the latest remote, linked in the #302 issue, I receive this information. Is it enough?

{
	"3": {
		"0": "IKEA of Sweden",
		"1": "TRADFRI on/off switch",
		"2": "",
		"3": "2.2.008",
		"6": 3,
		"9": 21
	},
	"5750": 0,
	"9001": "Larmet",
	"9002": 1576423909,
	"9003": 65549,
	"9019": 1,
	"9020": 1576423952,
	"9054": 0,
	"15009": [
		{
			"9003": 0
		}
	]
}

{
	isProxy: false,
	options: {},
	name: 'Larmet',
	createdAt: 1576423909,
	instanceId: 65549,
	type: 0,
	alive: true,
	lastSeen: 1576423952,
	otaUpdateState: 0,
	deviceInfo:
	 DeviceInfo {
	   isProxy: false,
	   options: {},
	   firmwareVersion: '2.2.008',
	   manufacturer: 'IKEA of Sweden',
	   modelNumber: 'TRADFRI on/off switch',
	   power: 3,
	   serialNumber: '',
	   battery: 21
	},
	switchList: [ Switch {
		 isProxy: false,
		 options: {},
		 name: '',
		 createdAt: 0,
		 instanceId: 0,
		 dimmer: 0,
		 onOff: false,
		 onTime: 0,
		 _accessory: undefined,
		 client: [TradfriClient
			]
		}
	]
}

**Comment by AlCalzone** [comment]
The device specific data is in the 15009 key. 9003 is the device ID, which is empty in this case. So there's really only the battery status to work with.
If you want to access the buttons, you'll have to take a look at a zigbee solution.

**Comment by WillooWisp** [comment]
I see, my thought as well. In this case it would be enough to know that a button has been pressed, since I only want to trigger a flow to start. Of course it would have been good to know if on or off button was pressed. But I guess to only know that any button was pressed it can still be used as a very price worthy single button device.

**Comment by AlCalzone** [comment]
You could watch the lastSeen state and see if that is always updated when a button is pressed.
