### ISSUE TITLE
Investigate Sonos integration

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-tradfri-client#288]
Raw message:
```json
{"3":{"0":"IKEA of Sweden","1":"SYMFONISK Sound Controller","2":"","3":"2.1.022","6":3,"9":60},"5750":8,"9001":"SYMFONISK Sound Controller","9002":1574167754,"9003":65542,"9019":1,"9020":1574167789,"9054":0,"15017":{"9115":["RINCON_949F3E1E4C8A01400"],"9117":232},"15018":[{"9003":0}]}
```

Should be in App v1.11

**Comment by justme-1968** [comment]
if the ikea speakers are completely sonos compatible (as i think they are) it is better to leave this to the sonos libs/plugins/integrations as it is a completely different animal as the zigbee part. doing sonos completely and right is a huge huge thing.

**Comment by AlCalzone** [comment]
At a first glance it looks like this message only has an identifier for the speaker. Not much I can do with that if the app doesn't give me more information. I'm definitely not going to integrate a Sonos protocol in this lib if that means more than sending a few CoAP messages for start/stop/pause/next/prev.
