### ISSUE TITLE
is it possible to set colortemperature or hue and saturation on a group?

### ISSUE THREAD

**Issue by justme-1968** [AlCalzone/node-tradfri-client#313]
is it possible to set colortemperature or hue and saturation on a group? 

it ist not listed in the group datastructure documentation. but is this a limitation of the gateway? the api? or is it just missing from the current node-tradfri-client implementation?

**Comment by AlCalzone** [comment]
This is a limitation of the gateway/API - the properties don't exist for the group endpoint. The tradfri adapter works around it by setting the values for each bulb in the group:
https://github.com/AlCalzone/ioBroker.tradfri/blob/master/src/main.ts#L353
