### ISSUE TITLE
Error: bind EADDRNOTAVAIL

### ISSUE THREAD

**Issue by RubenMeul** [AlCalzone/node-tradfri-client#328]
Hi, upon running the basic discoverGateway example, I'm having this issue. Can you help me out?

`(node:11198) UnhandledPromiseRejectionWarning: Error: bind EADDRNOTAVAIL fd6e:b0a:4804:1:c52:2e6e:664:2942%en0
    at dgram.js:334:20
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:11198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by AlCalzone** [comment]
That probably means port 5353 is already occupied by some other program.

**Comment by RubenMeul** [comment]
Checked ports in use, it's not used by any program, unfortunately.

**Comment by AlCalzone** [comment]
How many network interfaces do you have?

**Comment by AlCalzone** [comment]
Apparently this is fixed by an update of the `mdns-server` dependency. I'll update it and provide you with a new release to test.

**Comment by AlCalzone** [comment]
v2.1.1 should be available in a few minutes. Please test with that version and reopen if the issue still exists.

**Comment by AlCalzone** [comment]
Oh, and please also report back if it does work, so I can close the upstream issue.
