### ISSUE TITLE
Throws on observeGroupsAndScenes

### ISSUE THREAD

**Issue by CliffS** [AlCalzone/node-tradfri-client#33]
Hi.  Just got back to looking at this after a long break being busy.  I'm now using version 0.8.4 (which appears to be one **ahead** of Github).

After calling `client.observeGroupsAndScenes()`, I'm getting:

```
node_modules/node-coap-client/build/CoapClient.js:416
        block2Opt.isLastBlock = true; // not sure if that's necessary, but better be safe
                              ^

TypeError: Cannot set property 'isLastBlock' of undefined
    at Function.requestNextBlock (/home/cliff/src/git/ikea-tradfri/node_modules/node-coap-client/build/CoapClient.js:416:31)
    at Function.onMessage (/home/cliff/src/git/ikea-tradfri/node_modules/node-coap-client/build/CoapClient.js:581:40)
    at SocketWrapper.emit (events.js:159:13)
    at SocketWrapper.socket.on (/home/cliff/src/git/ikea-tradfri/node_modules/node-coap-client/build/lib/SocketWrapper.js:12:18)
    at Socket.emit (events.js:159:13)
    at Socket.udp_onMessage (/home/cliff/src/git/ikea-tradfri/node_modules/node-dtls-client/build/dtls.js:204:34)
    at Socket.emit (events.js:159:13)
    at UDP.onMessage (dgram.js:658:8)
```

Am I doing something wrong?

**Comment by CliffS** [comment]
At the point of the exception, `message.options` is:

```
[ StringOption {
    code: 11,
    name: 'Uri-Path',
    rawValue: <Buffer 31 35 30 30 35>,
    repeatable: true,
    minLength: 0,
    maxLength: 255 },
  StringOption {
    code: 11,
    name: 'Uri-Path',
    rawValue: <Buffer 31 36 39 32 37 35>,
    repeatable: true,
    minLength: 0,
    maxLength: 255 },
  StringOption {
    code: 11,
    name: 'Uri-Path',
    rawValue: <Buffer 32 30 30 34 36 38>,
    repeatable: true,
    minLength: 0,
    maxLength: 255 },
  NumericOption {
    code: 12,
    name: 'Content-Format',
    rawValue: <Buffer 32>,
    repeatable: false,
    maxLength: 2 } ]
```

**Comment by AlCalzone** [comment]
I have an idea what's going on. Please update your node-coap-client dependency to this version
https://github.com/AlCalzone/node-coap-client/tarball/fix-31
and check if it fixes your problem. If not, I'll have to add a bunch of debug logs.

**Comment by CliffS** [comment]
Seems to be the same with that version of node-coap-client.  Sorry.

It did start working for a bit (before installing fix-31) but I don't know why it worked nor wy it stopped again.

**Comment by AlCalzone** [comment]
Okay, can you log the traffic with Wireshark and try to reproduce the error while doing so?

**Comment by CliffS** [comment]
Hope this helps.  This is with the published version of node-coap-client.

[wireshark.zip](https://github.com/AlCalzone/node-tradfri-client/files/1761886/wireshark.zip)

**Comment by AlCalzone** [comment]
I think I found the problem. I request a resource, the gateway responds with a blockwise response. Now the client expects that the original request has the Block2 option, which it doesn't.

**Comment by AlCalzone** [comment]
Please try again with the most recent version of the branch I linked above.

**Comment by CliffS** [comment]
Yes.  That seems to work fine.

**Comment by AlCalzone** [comment]
Ok, I released the fix in `node-coap-client@v0.5.5`

**Comment by CliffS** [comment]
And again, please bump the requirement in `node-tradfri-client` and release.  Makes it much cleaner this end. :)

Thanks again for the speedy response.

**Comment by AlCalzone** [comment]
done!
