### ISSUE TITLE
Error during authentication: "The security code is wrong"

### ISSUE THREAD

**Issue by bohoffi** [AlCalzone/node-tradfri-client#35]
Using `"node-tradfri-client": "^0.8.5"` running a sample express app I get the above mentioned error message when calling the `authenticate` method using the security code printed on the back of my Gateway (between the lines "Security Code :" and "Serial Number: ".

Calling `ping` works fine.

**Comment by AlCalzone** [comment]
> the security code printed on the back of my Gateway (between the lines "Security Code :" and "Serial Number: ".

On my gateway, the serial number comes first (lowercase with dashes in between), and then the security code (A-Z, a-z, 0-9), 16 chars. Are you sure you have the correct one and you are not confusing a lowercase "L" with an uppercase "I" for example?

**Comment by bohoffi** [comment]
Maybe I've got an older/a newer hardware revision and that's why serial number and security code are switched.

The pattern of the security code you mentioned is matching the value passed to the `authenticate` method. I did not switch any letters or numbers.

**Comment by AlCalzone** [comment]
In that case I'll need a traffic log for port 5684 (e.g. from Wireshark) and probably your security code to check out what's going wrong.

**Comment by AlCalzone** [comment]
Mine has `1.3.14` too, so that's good. In Wireshark you have to select the network interface your PC is using to communicate with the network that has the gateway in it. As capture filter, enter `port 5684` or `host 192.168.0.7` (replace that with your gateway IP) and start capturing.

**Comment by bohoffi** [comment]
Now I used the filter `ip.dst == 192.168.1.100` (which is the IP address of the gateway) but there aren't any COAP requests listed. If I ping the gateway using cmd the request are captured.

`ping` request ist not logged/captured.

**Comment by AlCalzone** [comment]
> Now I used the filter `ip.dst == 192.168.1.100` (which is the IP address of the gateway) but there aren't any COAP requests listed. If I ping the gateway using cmd the requests are captured.

Wireshark has 2 kinds of filters. Capture filters (to be entered before you start a capture) and display filters (to be entered while viewing a capture). I think you entered a display filter. Can you try with the aforementioned capture filter `port 5684`?

> I could provide my code via a sample repo if that could help?

Yeah we can also try to do that.

**Comment by bohoffi** [comment]
Yes, you're right - I used a display filter. I will set a capture filter to check when I'm back home.
Additionally I will provide a sample repo.

**Comment by bohoffi** [comment]
Ok, I started capturing using the capture filter `port 5684` but nothing gets captured.
I've created a sample repo:
https://github.com/bohoffi/node-tradfri-client-express-sample
Removed Gateway address and security code.

**Comment by AlCalzone** [comment]
> Ok, I started capturing using the capture filter port 5684 but nothing gets captured.

Does your PC have multiple interfaces? If so, you need to select the correct one (usually distinguishable by the small traffic histogram).

I'll try your repo as soon as I get home.

**Comment by bohoffi** [comment]
Yes, 3 interfaces get displayed but only one (WLAN) indicates traffic. This was the one I selected for capturing.

**Comment by AlCalzone** [comment]
As a matter of fact, I'm getting the same error using your code. I'm trying to find out why.

**Comment by AlCalzone** [comment]
Nah, I just mistyped the code:
![unbenannt](https://user-images.githubusercontent.com/17641229/37107104-bc08377e-2233-11e8-84e0-62937ba4a49d.PNG)

Are you using the IP or hostname of the gateway to connect? For me, the hostname ("gw-", followed by the mac address without special chars) works better, some users reported that using the IP is more reliable.

**Comment by bohoffi** [comment]
THAT'S the point: using the gateways IP works :D

Thank you for that tip ;)

**Comment by AlCalzone** [comment]
No problem :)
