### ISSUE TITLE
Unable to connect to gateway (after Tradfri update?)

### ISSUE THREAD

**Issue by tomekc** [AlCalzone/node-tradfri-client#351]
My gateway stopped working with HomeKit and no longer works with code I wrote using `node-tradfri-client` (updated to 2.1.2).

The gateway is detected (version says **1.10.29**), but unable to connect

```
Error: Could not connect to the gateway:
An unexpected error occured while connecting to the gateway: received fatal alert: undefined
```

Can anyone confirm the issue? It worked for sure around November last year.

**Comment by AlCalzone** [comment]
I'll need a tcpdump to understand whats going on, which must include the connection initiation. I usually set it up with a filter on port 5684 to only capture the CoAP traffic. 
And I'll need your connection credentials to decrypt the communication.

**Comment by tomekc** [comment]
Sure, I'll try to collect. Can I decrypt the dump by myself?

**Comment by AlCalzone** [comment]
I think you can just upload the file here. You should also be able to decrypt it yourself. I might have posted the way to do that either here, or in https://github.com/AlCalzone/node-coap-client or in https://github.com/AlCalzone/node-dtls-client

**Comment by tomekc** [comment]
I think I found it. I made a longer break of playing with Tradfri, and the credentials have expired (they do after 6 weeks of inactivity, right?).

On the other hand, the exception could have been more descriptive.

**Comment by AlCalzone** [comment]
I'm pretty sure there is a message in place for wrong credentials, but maybe the response from the gateway has changed. I'll check it out.

**Comment by tomekc** [comment]
And there is sort of. I made an experiment and tried to provide wrong credentials in different ways.
 
`await tradfri.connect("foo", "bar");` results in *An unexpected error occurred while connecting to the gateway: received fatal alert: undefined*

I got *The provided credentials are not valid. Please re-authenticate!* error only in one case, when invalid PSK and correct identity was given: `await tradfri.connect(credentials.identity, "foo");`

But in case of the wrong identity, I'm back to unexpected error: `await tradfri.connect("foo", credentials.psk);`

**Comment by AlCalzone** [comment]
Closing this issue in favor of #352

**Comment by AlCalzone** [comment]
v2.1.4 should have a better error message for this.
