### ISSUE TITLE
Rename a device

### ISSUE THREAD

**Issue by tuebben** [AlCalzone/node-tradfri-client#391]
Hello,

it would be very nice if someone could show me an example that can be used to rename a Device.

Thanks in Advance & Greetings ... Peter

**Comment by AlCalzone** [comment]
Its actually very similar to [renaming a group](https://github.com/AlCalzone/node-tradfri-client#rename-a-group):
```js
// accessory is the previously stored instance of your device:
const newAccessory = accessory.clone();
newAccessory.name = newName;
await tradfri.updateDevice(newAccessory);
```

**Comment by tuebben** [comment]
@AlCalzone : Great, works perfectly.

Thanks a lot! 🤗
