### ISSUE TITLE
Official IKEA Tradfri app gets disconnected when using the authenticate() method

### ISSUE THREAD

**Issue by simonknittel** [AlCalzone/node-tradfri-client#394]
Heyho!

I'm having trouble with the authentication process.

When I use the authenticate() method with provided security code, I get returned a working identity and psk. Using them to toggle lights works fine.

But, at the same moment the official Tradfri app from IKEA gets disconnected with following error message: "As a security  precaution, you have been disconnected from your gateway." Then, when I reconnect the app, the previously retrieved identity and psk get invalid (error code 2 when using connect()).

Anything that I'm not understanding correctly?

**Comment by AlCalzone** [comment]
Hmm that is something new. I guess the gateway now disallows having multiple active identities. Not sure if I can do anything about that.

**Comment by simonknittel** [comment]
Any way I can help you debugging with this issue? I've also got a different app on my phone (Hue Essentials) which works fine the whole time. No need to reconnect etc.

**Comment by AlCalzone** [comment]
If you could capture that app's traffic ( I think port 5684) and send me that plus your security code, I can take a look.

**Comment by simonknittel** [comment]
Which app? IKEA's official one, that Hue Essentials one or _my_ one?

**Comment by AlCalzone** [comment]
The Hue app, preferably standalone and also while you connect with the one using node-tradfri-client.

**Comment by simonknittel** [comment]
I've sent you the two captures incl. the security code to the email you provided in your package.json. I hope that helps.

**Comment by AlCalzone** [comment]
Did you have success finding the PSK for Hue Essentials?

**Comment by simonknittel** [comment]
Oh, sorry. Totally forgot 🙃 After some more experimenting the PSK for Hue Essentials also got invalid! And now it behaves the same like my code. So whenever I connect Hue Essentials or create a new Identity+PSK with my code, it will disconnect the official IKEA Tradfri app. When I reconnect the official app, my credentials will get invalid.

BUT, from an older test I got a still working identity + PSK which does not disconnect the official app.

So, it looks like there are maybe two types of credentials or so? Or old ones don't have some kind of expiration date or some kind of concurrent credentials limit? I don't know...

**Comment by AlCalzone** [comment]
That might be... The first time I had a report of expired credentials was a few months ago https://github.com/AlCalzone/node-tradfri-client/issues/351#issuecomment-589418571
Maybe there's also a limit on the number of active credentials now 😕

**Comment by simonknittel** [comment]
Is there a way to clear all active credentials? In the very early stages of my code I requested new credentials on every request. Maybe because of that I kinda filled up the limit?

**Comment by AlCalzone** [comment]
Not to my knowledge - maybe there's a hidden command for that.

**Comment by simonknittel** [comment]
FYI: I can't reproduce the issue anymore. Maybe it's actually been a bug in the firmware software of the gateway and got fixed in the meantime.
