### ISSUE TITLE
tradfri.authenticate() hangs

### ISSUE THREAD

**Issue by laurilubi** [AlCalzone/node-tradfri-client#4]
I downloaded the current latest nodejs for Windows and node-tradfri-client. I run node from the command prompts and test the commands directly.

I have identified my IKEA gateway by IP, via checking in the router clients lists.
```
const tradfri = new TradfriClient("192.168.1.xxx");
{identity, psk} = tradfri.authenticate("_SecurityCode_");
```
After that I only see `"..."` and nothing ever happens. I removed the `await `from the examples as I am not in an `async `function.
Any ideas?

Gateway firmware version 1.2.42

**Comment by AlCalzone** [comment]
Just removing the `async` keyword doesn‘t cut it, you have to use the `then` method of the returned promise. An example can be found in the readme just above the authentication section.

**Comment by laurilubi** [comment]
Thanks. I got connected now. One step closer to controlling the lamps.

It seems like I have a problem with typescript code as some of your examples seem to be in typescript, but my nodejs only supports javascript. I will not bother you with this. I will search for some good tutorials to get it working one day. Thanks.

**Comment by AlCalzone** [comment]
Actually its just a newer syntax that will be in "standard" JavaScript some day (EcmaScript 7/2017). Its more concise, so I used it to get the documentation out there. And TypeScript has the added bonus that I can convey to the reader what data types the functions expect.
When I have some free time, I'll update the docs to include "vanilla" JavaScript
