### ISSUE TITLE
Support discovery

### ISSUE THREAD

**Issue by neophob** [AlCalzone/node-tradfri-client#40]
Thanks for this library! I was looking for a way to discover all controllers - which seems to be possible using mdns/bonjour. should I create a PR or are there other ways discovering tradfri controllers?

cheers

**Comment by AlCalzone** [comment]
I haven't looked into that yet, although it would be nice. If you have a way or want to create PR, go for it.

**Comment by neophob** [comment]
Well not a PR yet but a propsal. using the `bonjour` module it's quite easy:

```
'use strict';

const bonjour = require('bonjour')();

const MDNS_NAME = 'coap';

function findTradfri() {
  return new Promise((resolve, reject) => {

    function serviceUpListener(service) {
      if (!service || !service.txt || !service.name.startsWith('gw-')) {
	return;
      }
      const foundDevice = {
        name: service.name,
        version: service.txt,
        addresses: service.addresses
      }
      resolve(foundDevice);
    }
    const mdnsBrowser = bonjour.findOne({ type: MDNS_NAME, protocol: 'udp' }, serviceUpListener);
    mdnsBrowser.start();
  });
}

findTradfri()
  .then((result) => {
    console.log('entry found', result);
  });
```

I'm not very into TS, should I create an additional .js file for the discovery or do you want a ts version?

**Comment by AlCalzone** [comment]
As TypeScript is basically JS, you can just provide a TS file with JS code and I'll transform it to my liking. Or add a `static` method to the `TradfriClient` class.
