### ISSUE TITLE
setColorTemperature does not affect real bulb when it's off

### ISSUE THREAD

**Issue by honzabrecka** [AlCalzone/node-tradfri-client#436]
Steps to reproduce:

1. set color temperature to 0
1. turn off
1. set color temperature to 100
1. turn on

Bulb remains cold, while it should be warm. And it reports that its temperature is 100.

Color temperature can be set only if the light is on.

**Comment by AlCalzone** [comment]
Not sure if there is anything that I can do about that. 

Setting the new color temperature when turning on might require caching commands until they have an effect.

**Comment by honzabrecka** [comment]
Thanks for your reply.

I can enqueue commands myself, but it won't solve the situation when one turns on the light with paired switch. I mean without blink - enqueued changes can be applied once the light is turned on, but it will likely cause that observable blink.

That (changed, but not really) colorTemperature value is from gateway itself or is it somehow cached by this library?

**Comment by honzabrecka** [comment]
It is probably a bug in a bulb or in a gateway as I observed that:
1. hue/saturation can be set and are respected when the light is turned on
1. even IKEA app thinks that the temperature is warm (even though it is not)

**Comment by AlCalzone** [comment]
>     2\. even IKEA app thinks that the temperature is warm (even though it is not)

That is very likely a gateway bug then. All values this library has are received directly from the gateway.
