### ISSUE TITLE
Potential unhandled rejection in `ping`

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-tradfri-client#48]
See https://github.com/AlCalzone/node-tradfri-client/issues/46#issuecomment-372306606
This should never happen.

**Comment by neophob** [comment]
I could not reproduce that error anymore with the `ping` function. I tried disconnecting wifi and rebooting the gateway and sending commands, so I guess we can close

**Comment by AlCalzone** [comment]
I double-checked the code and cannot find any reason why it would reject.
