### ISSUE TITLE
Any news about support for motion sensor?

### ISSUE THREAD

**Issue by yocal** [AlCalzone/node-tradfri-client#495]
I would love to use my motion sensor - but as far as I can see is it not yet supported.

Any news on that? Or maybe some hints of where I could start looking if I wanted to lend a hand?

**Comment by AlCalzone** [comment]
AFAIK the motion sensors are not exposed by the gateway, so it isn't possible.

**Comment by yocal** [comment]
I guess I could hook it up via the app so it'll update a dummy-bulb hidden somewhere out of sight - and then use that accessory update request as a trigger for something else. Wouldn't that work? 🤔

**Comment by AlCalzone** [comment]
Sounds like it could work. You'll have the extra bulb though.

**Comment by yocal** [comment]
#workaround :P

**Comment by yannik-b** [comment]
For several weeks my TRADFRI motion sensor is exposed in Apple HomeKit - so maybe it is possible to retrieve motion sensor events with the newest firmware?

**Comment by AlCalzone** [comment]
If anyone has information on that, let me know.
The library uses the same interface as the "Home Smart" App, where I couldn't find anything new regarding motion sensors yet.
