### ISSUE TITLE
observeGroupsAndScenes() returns a promise

### ISSUE THREAD

**Issue by CliffS** [AlCalzone/node-tradfri-client#5]
What is the purpose of returning a promise from `tradfri.observeGroupsAndScenes()` and `tradfri.observeDevices()`?

The promise appears to resolve back to the original `tradfri` variable.  in your example, you appear to ignore the return value of these two functions.  Is there any downside in doing so?  Is there any upside in having a `.then()`?

**Comment by AlCalzone** [comment]
By using the returned promise, you can check if the gateway acknowledged the observe request. When it resolves, you know the gateway **will send** updates. And you can catch promise rejections (e.g. if the connection went down).

**Comment by CliffS** [comment]
OK.  Makes sense.  Thanks.
