### ISSUE TITLE
`device updated` events during transition time

### ISSUE THREAD

**Issue by Pajn** [AlCalzone/node-tradfri-client#505]
I get additional `device updated` events that I do not expect and I can only find transition time as the possible explanation.

For example:
I have a light at 100% brightness
I set the brightness to 82%
I get three `device updated` events where the dimmer value is `81.9`, `96.5` and finally `81.9` again.

**Comment by AlCalzone** [comment]
It is expected that we get intermediate events during a transition, however the premature `81.9` seems off.

However, without having a `tcpdump` or something I can only assume that this is what the gateway sends us. Not trusting what it sends could quickly lead down a rabbit hole of heuristics I'm afraid.

**Comment by Pajn** [comment]
Hmm, I'll have to workaround that then.

The premature `81.9` is actually nice, if it is consistent I can take the first event of a batch and still get rapid updates. Though it doesn't sound like it is. Guess I'll take the last after a 2 second quite period instead.

Thank you for the information!
