### ISSUE TITLE
Can no longer connect after being shut off during vacation

### ISSUE THREAD

**Issue by yocal** [AlCalzone/node-tradfri-client#532]
I think my setup took advantage of me being away...

I shut down the IKEA gateway and my RPi while I was away on summer vacation. When I came home I fired it all up and went about my day. I didn't notice my controller on the RPi (using the node-tradfri-client) wasn't connected as IKEAs own app worked fine.

When I found out and investigated it turned out I'm getting:

`TradfriError: The gateway did not respond in time.`

I've tried connecting using hostname and direct IP address but nothing works. I've tried using the discoverGateway function and tried connecting to the .host from there, and I've tried using the IPv4 directly. 

I can ping both hostname and IP of the gateway successfully from the machine it's running on, and I've tried running the code on several machines.

What could have happened? Any changes in the newest version or something strange? I've tried using .authenticate() too with the security code, but that times out as well.

**Comment by yocal** [comment]
Looks like there was a breaking change during my time off - noticed the version was bumped to 3.x, upgraded and everything connects and works right off the bat... 

So I'll just crawl back into my cave and enjoy the light show 😅

**Comment by AlCalzone** [comment]
Just for completeness sake:
Ikeas firmware updates introduced a bug in their DTLS implementation which caused this lib to stop connecting. We now allow this incorrect behavior once during connection.
