### ISSUE TITLE
Restore all previously active observations after a `reset()` call

### ISSUE THREAD

**Issue by neophob** [AlCalzone/node-tradfri-client#59]
Use case:

the tradfri gateway is reset, this is handled by this library. but you current lamp/group/scene state might be out of sync. 
Goal would be that this library provides a call that uses the existing callback (`device updated` etc.) and provides up to date functions.

**Comment by AlCalzone** [comment]
Yeah, that's on my list. It's what I meant in the last bullet point there: https://github.com/AlCalzone/node-tradfri-client/issues/47#issuecomment-372295317

It is not yet included in the reconnection PR but definitely something I want to implement. For now you can just listen for the `"reconnecting"` and the `"connection alive"` event. If the connection becomes alive after a reconnection, you have to re-call the `observeXYZ` methods.
The event handlers you registered with `on("device updated")` etc. should still be attached and should be called when you re-observe.

**Comment by AlCalzone** [comment]
... aaand this is released in v0.12.2
