### ISSUE TITLE
Question about initialisation

### ISSUE THREAD

**Issue by CliffS** [AlCalzone/node-tradfri-client#6]
Currently I am setting up to use the library by listening on all all six possible events and then calling `observeDevices()` and `observeGroupsAndScenes()` in a `Promise.all()`.  The gateway responds by emitting an event for each device, group and scene which I use to initialise my data structure.  However the promise resolves immediately, returning the `TradfriClient` class.

My question is: Is there any way to know when the initialisation phase is over?  For example, is there a way to find in advance the number of devices, groups and scenes to expect?  Or could there be an event triggered to indicate that initialisation is finished?  Or perhaps could the resolution of the promises returned by `observeDevices()` and `observeGroupsAndScenes()` be deferred until after the initialisation is complete?

**Comment by AlCalzone** [comment]
Good point.
I could raise an event `"device list updated"` (and similar for groups) inside `observeDevices_callback`, you can subscribe to with `tradfri.once(...)`. That way you know how many `"device updated"` events to expect.
But I don't particularly like that, it feels unclean. 

Your proposal for deferring the promise resolution seems solid. I'll have to think a bit about it, but I don't expect any downsides.

**Comment by CliffS** [comment]
Deferring the promise resolution would be perfect.  I currently have an `await sleep(3)` in my `.then()` which is less than perfect. :)

**Comment by AlCalzone** [comment]
Working on it. Deferring groups/scenes is a bit more complicated. And I need to find a way to restore the test functionality.
