### ISSUE TITLE
Gateway dont respond in time

### ISSUE THREAD

**Issue by 50l3r** [AlCalzone/node-tradfri-client#65]
I cant connect to my gateway using this code:

```
import { TradfriClient, Accessory, AccessoryTypes, discoverGateway } from "node-tradfri-client";

discoverGateway().then((response) => {
	console.log("Pasarela " + response.name+ " encontrada");

	var tradfriClient = new TradfriClient(response.name);

	tradfriClient.authenticate("XXXXXXXXXXXXXX").then((response) => {
		console.log("OK");
		console.log(response);
	}).catch((e) => {
        console.log(e);
    });
});
```

This is the error:

```
{ Error: The gateway did not respond in time.
    at TradfriError (D:\Git\tradfri\node_modules\node-tradfri-client\build\lib\tradfri-error.js:12:9)
    at TradfriClient.<anonymous> (D:\Git\tradfri\node_modules\node-tradfri-client\build\tradfri-client.js:143:39)
    at next (native)
    at fulfilled (D:\Git\tradfri\node_modules\node-tradfri-client\build\tradfri-client.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) code: 1 }
```

**Comment by AlCalzone** [comment]
It seems that some users can only connect to their gateway using IP addresses, while others can only use the hostname. Can you try changing
`var tradfriClient = new TradfriClient(response.name);`
to
`var tradfriClient = new TradfriClient(response.addresses[0]);`
?

**Comment by 50l3r** [comment]
It works 👍 

How can i list all devices?

**Comment by AlCalzone** [comment]
> How can i list all devices?

It's all in the docs ;)
https://github.com/AlCalzone/node-tradfri-client#subscribe-to-updates
and 
https://github.com/AlCalzone/node-tradfri-client#observe-devices
if you want to continuously interact with the devices (this is recommended). The event "device updated" will be emitted for every device you have.

In case you only want to get all device IDs once, you can issue a [custom request](https://github.com/AlCalzone/node-tradfri-client#custom-requests) to the path `"15001"`.

**Comment by 50l3r** [comment]
When i try to execute this code: https://github.com/AlCalzone/node-tradfri-client#subscribe-to-updates

```
import { TradfriClient, Accessory, AccessoryTypes, discoverGateway, TradfriErrorCodes } from "node-tradfri-client";

discoverGateway().then((response) => {
	console.log("Pasarela " + response.name+ " encontrada");

	var tradfri = new TradfriClient(response.addresses[0]);

	tradfri.authenticate("xxxxxxxxxxxx").then((response) => {
		console.log("AUTENTICADO");

		// observe devices
		tradfri
		    .on("device updated", tradfri_deviceUpdated)
		    .on("device removed", tradfri_deviceRemoved)
		    .observeDevices()
		;

		const lightbulbs = {};
		function tradfri_deviceUpdated(device) {
		    if (device.type === AccessoryTypes.lightbulb) {
		        // remember it
		        lightbulbs[device.instanceId] = device;
		    }
		}

		function tradfri_deviceRemoved(instanceId) {
		    // clean up
		}

		// later...
		// at least after we have actually received the light object

		const light = lightbulbs[65537].lightList[0];
		// blink
		setTimeout(() => light.toggle(), 0);
		setTimeout(() => light.toggle(), 1000);
		setTimeout(() => light.toggle(), 2000);
		setTimeout(() => light.toggle(), 3000);

		// even later...
		// before shutting down the app
		tradfri.destroy();
	}).catch((e) => {
       switch (e.code) {
           case TradfriErrorCodes.ConnectionTimedOut: {
               console.error("Se supero el tiempo de espera en la conexion");
           }
           case TradfriErrorCodes.AuthenticationFailed: {
               console.error("Autenticación fallida");
           }
           case TradfriErrorCodes.ConnectionFailed: {
               console.error("Conexion fallida");
           }
       }
    });
});
```

I recieve: 

`Pasarela gw-a0cc2b6d7bf5 encontrada
AUTENTICADO
(node:12044) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: unexpected response (4.01) to observeDevices():`

**Comment by AlCalzone** [comment]
I guess the docs could be a bit more specific here.
You only have to authenticate once (at least until you get an error that says otherwise) and you should store the returned identity and psk.

Once you're authenticated, you need to actually connect using the identity and psk, before you can issue any commands:
https://github.com/AlCalzone/node-tradfri-client#connecting-to-the-gateway

And that part
```
// later...
// at least after we have actually received the light object

const light = lightbulbs[65537].lightList[0];
// blink
setTimeout(() => light.toggle(), 0);
setTimeout(() => light.toggle(), 1000);
setTimeout(() => light.toggle(), 2000);
setTimeout(() => light.toggle(), 3000);

// even later...
// before shutting down the app
tradfri.destroy();
```
won't work because you have to wait until you received a light object before using it.

**Comment by 50l3r** [comment]
U are right, connect and works like a charm :)

Mucha thanks

**Comment by AlCalzone** [comment]
No worries, glad I could help

**Comment by rosek86** [comment]
Hi, can you add info about IP address to the Readme, please? It'd save me an hour, and I'm sure it will be useful for others too :-)

Regards

**Comment by AlCalzone** [comment]
Sure thing => 9564565

**Comment by rosek86** [comment]
Many thanks!
