### ISSUE TITLE
Invalid error message when gateway is unconfigured?

### ISSUE THREAD

**Issue by neophob** [AlCalzone/node-tradfri-client#66]
I try to pair with a new Gateway (currently I don't have the remote, so I cant pair any lamps) - when I run this script:
```
const { TradfriClient, discoverGateway, AccessoryTypes } = require('node-tradfri-client');

var libraryOptions = {
  customLogger: (m,s) => { console.log('>>',s,m); }
};
const hostname = 'gw-a0xx...';
const securityCode = '<redacted>'
let security;
const tradfri = new TradfriClient(hostname, libraryOptions);
tradfri.authenticate(securityCode)
  .then((sss) => {
   console.log('sec', sss);
    security = sss;
    return tradfri.connect(security.identity, security.psk);
  })
  .then(() => {
    debug('LGTM, connected!');
  }).catch((err) => {
    console.log('ERR', err.message);
  })

```

it shows this error:
```
>> debug authenticate() > trying to connect with the security code
>> debug Attempting connection. Identity = Client_identity, psk = <redacted>
>> debug Connection failed. Reason: timeout
ERR The gateway did not respond in time.
```

could it be, that this error message is wrong?

**Comment by AlCalzone** [comment]
> could it be, that this error message is wrong?

Maybe. To confirm please run your script with the following command-line and post the logs here:
```bash
# on linux:
DEBUG=node-*-client node main.js
# on Windows:
set DEBUG=node-*-client && node main.js
```
where main.js is your script name.

**Comment by neophob** [comment]
jep just did that:

```
  node-tradfri-client [DEBUG] Attempting connection. Identity = Client_identityfoo, psk = <redacted>, this.requestBase = coaps://gw-a0xx...:5684/ +4ms
  node-coap-client getConnection(coaps://gw-a0xx...:5684) => establishing new connection +4ms
  node-coap-client socket creation for origin coaps://gw-a0xx...:5684 failed: Error: getaddrinfo ENOTFOUND gw-a0xx... +11ms
  node-coap-client socket creation for origin coaps://gw-a0xx...:5684 failed: Error: getaddrinfo ENOTFOUND gw-a0xx... +2ms
  node-coap-client socket creation for origin coaps://gw-a0xx...:5684 failed: Error: getaddrinfo ENOTFOUND gw-a0xx... +1ms
  node-coap-client tryToConnect(coaps://gw-a0xx...:5684) => failed with error: Error: getaddrinfo ENOTFOUND gw-a0xx... +0ms
  node-tradfri-client [DEBUG] Connection failed. Reason: timeout +15ms
```

**Comment by AlCalzone** [comment]
Well, the gateway is actually not answering. Try the IP address, afaik some users have trouble connecting by hostname, while some have trouble connecting by IP - might be related to the gateway revision.

**Comment by neophob** [comment]
Firmware version is - according to the mdns record v1.3.14.
You was right, connecting with the ip works like a charm.... wtf.

**Comment by neophob** [comment]
Just one wild guess, running discovery, the gateway returns `addresses: [ '10.0.0.94', 'fe80::a2cc:2bff:fef8:535d' ] }` - it looks like it exposes its link-local ipv6 address, that might be an actual bug on the gateway

**Comment by AlCalzone** [comment]
> it exposes its link-local ipv6 address, that might be an actual bug on the gateway

Mine does that too, but it only sends that to my PC's IPv6 address, so the current discovery doesn't work. What's the problem with exposing the IPv6 address? I'm not too familiar with that.

**Comment by neophob** [comment]
not sure, but the "fe80::" address is a link-local address (think the 127.0.0.1 of ipv6). so it might be that the name is mapped either to the working ipv4 address or to the non working ipv6 address. its not defined who "wins" when you query the name, so name resolution might work or not.
as a current workaround, I guess I stick to using the ipv4 address - then it at least works as long no ip change happens.

**Comment by neophob** [comment]
ok, second gateway works without any issues (ping gw-a0cc.. works, so is ping ip).

-> guess thats related to the gateway firmware
