### ISSUE TITLE
Remote events

### ISSUE THREAD

**Issue by Julius-Bendt** [AlCalzone/node-tradfri-client#662]
Is it posible to get events from the tradfri remotes that Ikea makes? I have a few of the first gen remote (the round ones), and I would like to group these events to actions outside the Ikea ecosystem.

Would it be easier to set something like Zigbee2MQTT up instead?

**Comment by AlCalzone** [comment]
Unfortunately not possible: https://github.com/AlCalzone/node-tradfri-client/issues?q=is%3Aissue+is%3Aclosed+remote
You'll have to use Zigbee for that.
