### ISSUE TITLE
Not seeing changes for whole group

### ISSUE THREAD

**Issue by CliffS** [AlCalzone/node-tradfri-client#9]
I have a group with eleven bulbs and one remote control.

I am watching for changes with `observeDevices()`.  When I operate the lights from the remote control or from the Android app, I consistently get nine responses.  Two of the bulbs fail to be reported; always the same two bulbs.  If I control these bulbs individually from the app, they report correctly.

Is this a problem with the library or with the controller?

**Comment by AlCalzone** [comment]
Please set your DEBUG environment variable to "node-*-client" and post the console output when operating the group. I guess the problem is on the gateway side, but better be sure.

On Linux:
```
DEBUG=node-*-client node yourapp.js
```

On Windows:
```
set DEBUG=node-*-client & node yourapp.js
```

**Comment by CliffS** [comment]
Will do.  Thanks.  BTW, if I'm annoying you with all these issues, please say.  Otherwise I have a couple more to post.

**Comment by AlCalzone** [comment]
Nah, totally fine. I like that my lib is actually being used.

**Comment by CliffS** [comment]
Testing this will have to wait for daylight.  People are getting upset about me turning the lights on and off. :)

**Comment by AlCalzone** [comment]
Any news?

**Comment by CliffS** [comment]
I'm sorry, I haven't had time to work on the Tradfri stuff recently.  I won't until next Wednesday at the earliest.

**Comment by AlCalzone** [comment]
Sure, no worries

**Comment by CliffS** [comment]
OK.  It seems that Ikea's warning of *only ten devices per group* is about right.  Odd things happen if there are more than nine bulbs and one remote.  Breaking it into two groups solved the problem.  I'm going to close this as irrelevant to your code.
