### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by realjax** [AlCalzone/node-tradfri-client#93]
I'm having issues where it seems that he gateway considers devices to be alive when they really aren't. Sometimes when I switch off the power to a bulb I do get alive = false messages but more often alive remains true..  
What could be the reason for this ?

**Comment by AlCalzone** [comment]
I'm not entirely sure about the reason, but that seems to be one thing ZigBee devices have in common. The gateway seems to assume the device is still alive until it stops responding to requests. Until then, it seems the device state is not updated unless the device sends it itself.

**Comment by realjax** [comment]
Ok.  That's a bit of a hummer.  Well.. have to think of a workaround then. Maybe I can, at an intrerval, change the brightness with 1 percent or something and detect it that way..  thanks!

On June 8, 2018 5:14:21 PM GMT+02:00, AlCalzone <notifications@github.com> wrote:
>I'm not entirely sure about the reason, but that seems to be one thing
>ZigBee devices have in common. The gateway seems to assume the device
>is still alive until it stops responding to requests. Until then, it
>seems the device state is not updated unless the device sends it
>itself.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AlCalzone/node-tradfri-client/issues/93#issuecomment-395792655

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by AlCalzone** [comment]
Did your workaround work?

**Comment by realjax** [comment]
Yes it did. However I can no longer monitor the device automatically because messages started flooding

**Comment by realjax** [comment]
The node in node red can be automatically notified when the status of the light changes. Effectively passing all properties of the lamp back into the node. But those messages seemed to exponentially grow very fast due to my workaround.

**Comment by AlCalzone** [comment]
> But those messages seemed to exponentially grow very fast due to my workaround

Seems like you or the lib you use registers additional listeners when it shouldn't. In #95 there was a similar issue due to faulty handling of the reconnection in user code.

> 'Retransmit counter exceeded'

Means that the messages get lost and the lib tries to send them again until a configured maximum. For you this probably means that the bulb is offline. Not sure how you can handle this in node-red though.

**Comment by realjax** [comment]
> Means that the messages get lost and the lib tries to send them again until a configured maximum. For you this probably means that the bulb is offline. 

Cool, good to know. After this error messages appears the node red implementation stops responding all together, no matter the state of the light. The only way to get things working again  is to restart the node red daemon.  Is there a way I can avoid that  ?

**Comment by AlCalzone** [comment]
I guess you have to open an issue in the repo for the node-red integration. I need to have some way of notifying the senders that their messages got lost and rejecting the promises is the most elegant way imo. Users of the lib just need to catch those
