### ISSUE TITLE
message flood

### ISSUE THREAD

**Issue by neophob** [AlCalzone/node-tradfri-client#95]
I discovered that sometimes a gatway (running v1.4.15) floods my controller with alot of changes. i didn't count but I recieved more than 20 notifications/s for the same listener.

I don't have more information about this case as i cannot reproduce this, but I will update this ticked as soon as I find out more

**Comment by AlCalzone** [comment]
Thanks! Let me know if you find out what's going on.

**Comment by AlCalzone** [comment]
Regarding the double emit after a gateway reboot: Do you have automatic reconnection (as per the docs) enabled? In that case, the library tries to restore the observers and their callbacks itself. If you now add your own listeners, they will get called twice.

**Comment by neophob** [comment]
yes i use the reconnection option

```
const TRADFRI_PING_TIMEOUT_MS = 2000;

const libraryOptions = {
  watchConnection: {
    pingInterval: TRADFRI_PING_TIMEOUT_MS,
    failedPingCountUntilOffline: 3,
  },
};
```

So you're saying basically the `_startObserve` call in the `tradfriConnectionAlive` is the problem - as you said it tries to reconnect?

If thats the case - good ;) then I will probably create a PR to update the docs.

**Comment by AlCalzone** [comment]
Basically, yes. The information is already in the docs, albeit a bit hidden:
https://github.com/AlCalzone/node-tradfri-client#automatically-watching-the-connection-and-reconnecting => scroll down to the bottom.

> The automatic reconnection tries to restore all previously defined observers as soon as the connection is alive again.

**Comment by neophob** [comment]
True Story thanks. However I call `tradfriClient.clearObservers();` before I register my callbacks - shouln't that clear all observers?

**Comment by AlCalzone** [comment]
You're right - I missed that. Do you keep getting two updates per bulb after the reboot or is that just a one-time thing?

**Comment by neophob** [comment]
thanks @AlCalzone make sense!
