### ISSUE TITLE
An unknown error occured while connecting to the gateway

### ISSUE THREAD

**Issue by neophob** [AlCalzone/node-tradfri-client#98]
After some days my gateway started to respond only with "An unknown error occured while connecting to the gateway" - I don't see any other information logged.

After I restart my application the error went away. Does it make sense that the lib automatically tries to reconnect when "An unknown error occured while connecting to the gateway" happend? 

Does it make sense to emit this error with more details?

**Comment by AlCalzone** [comment]
That does make sense indeed. The error was probably lost somewhere on the way from node-dtls-client to node-coap-client to node-tradfri-client. I'll check it out.

**Comment by AlCalzone** [comment]
In the upcoming v1.3.0 (about to be released in a few seconds) `TradfriError`s with code `ConnectionFailed` now include the original error details.

**Comment by AlCalzone** [comment]
Automatic retrying of the initial connection on "unexpected error" will be shipped in v1.3.2
